"""
Phase 5.1 — Growth loop tracking.

Records one JSONL event each time an authenticated caller hits an
endpoint with a ``?ref=<code>`` query parameter. The goal is to
identify which referral / distribution sources actually drive
active users (not just pageviews), without storing any personal
data at all.

Privacy posture (identical to the Phase 4.9 conversion log):
  * Raw API keys are **never** persisted. Only
    ``SHA-256(api_key)[:32]``, which matches the
    ``_hash_api_key`` digest used by server / billing / conversion
    so BI pipelines can join the four files on one column.
  * No IP, no User-Agent, no email, no name, no card data ever
    enters a record — the only inputs are the opaque api-key
    hash, the caller-supplied ref_code, the HTTP path, and the
    request_id generated by Phase 4.4.
  * A leak-guard test plants unique-marker strings in the raw
    inputs and asserts they never appear in the growth file.

Failure posture:
  * All I/O is best-effort — a disk failure never breaks the
    underlying API request.
  * Thread-safe via a module-level ``threading.Lock``.
  * Dedup by ``(api_key_hash, ref_code)`` within a sliding 24h
    window — a chatty client that reloads the same ``?ref=``
    URL repeatedly is counted once.

Env vars:
    TRADING_API_GROWTH_LOG_PATH   JSONL output path
                                  (default: data/api_growth.jsonl)

CLI:
    python -m trading_bot.api.growth --summary
    python -m trading_bot.api.growth --summary --json
    python -m trading_bot.api.growth --summary --path path/to.jsonl
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import threading
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Optional, Union

import structlog

log = structlog.get_logger(__name__)


# ---------------------------------------------------------------------------
# Config + module state
# ---------------------------------------------------------------------------

GROWTH_LOG_ENV_VAR = "TRADING_API_GROWTH_LOG_PATH"
DEFAULT_GROWTH_LOG_PATH = "data/api_growth.jsonl"

DEDUP_WINDOW_HOURS = 24
DEDUP_WINDOW_SECONDS = DEDUP_WINDOW_HOURS * 60 * 60

# ref_code sanitisation. Accept alnum, -, _, :, . and cap length.
REF_CODE_MAX_LENGTH = 64
import re  # noqa: E402
_REF_CODE_STRIP_RE = re.compile(r"[^A-Za-z0-9\-_:.]")

# In-memory dedup cache: {(api_key_hash, ref_code): last_event_utc}.
# Rehydrated lazily from disk so dedup survives a process restart.
_dedup_cache: dict[tuple[str, str], datetime] = {}
_dedup_loaded_from: Optional[Path] = None
_write_lock = threading.Lock()


# ---------------------------------------------------------------------------
# Pure helpers
# ---------------------------------------------------------------------------


def _hash_api_key(api_key: Optional[str]) -> str:
    """SHA-256[:32] — identical to server/billing/conversion hashers."""
    if not api_key:
        return ""
    return hashlib.sha256(str(api_key).encode("utf-8")).hexdigest()[:32]


def _growth_log_path() -> Path:
    return Path(
        os.getenv(GROWTH_LOG_ENV_VAR, DEFAULT_GROWTH_LOG_PATH)
    )


def _sanitize_ref_code(raw: Optional[str]) -> str:
    """
    Strip to the documented safe character set, cap length. Untrusted
    input — a caller can put anything in a query param.
    """
    if raw is None:
        return ""
    s = str(raw)
    if not s:
        return ""
    cleaned = _REF_CODE_STRIP_RE.sub("", s)[:REF_CODE_MAX_LENGTH]
    return cleaned


def _parse_iso_utc(ts: Optional[str]) -> Optional[datetime]:
    if ts is None:
        return None
    s = str(ts).strip()
    if not s:
        return None
    try:
        if s.endswith("Z"):
            s = s[:-1] + "+00:00"
        dt = datetime.fromisoformat(s)
    except Exception:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt


def _load_dedup_cache(
    path: Path,
    *,
    now: datetime,
    window_seconds: int = DEDUP_WINDOW_SECONDS,
) -> dict[tuple[str, str], datetime]:
    """
    Rebuild the dedup set from any existing on-disk records whose
    timestamps fall inside the window. Corrupt / malformed lines
    are silently skipped.
    """
    if not path.exists():
        return {}
    out: dict[tuple[str, str], datetime] = {}
    threshold = now - timedelta(seconds=window_seconds)
    try:
        raw = path.read_text(encoding="utf-8")
    except Exception:
        return {}
    for line in raw.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        try:
            rec = json.loads(stripped)
        except Exception:
            continue
        if not isinstance(rec, dict):
            continue
        ts = _parse_iso_utc(rec.get("timestamp"))
        if ts is None or ts < threshold:
            continue
        h = rec.get("api_key_hash")
        ref = rec.get("ref_code")
        if not (h and ref):
            continue
        key = (str(h), str(ref))
        prev = out.get(key)
        if prev is None or ts > prev:
            out[key] = ts
    return out


def _ensure_dedup_loaded() -> None:
    """Rehydrate the dedup cache if the configured path has changed."""
    global _dedup_loaded_from
    path = _growth_log_path()
    with _write_lock:
        if _dedup_loaded_from != path:
            _dedup_cache.clear()
            _dedup_cache.update(
                _load_dedup_cache(
                    path, now=datetime.now(timezone.utc),
                )
            )
            _dedup_loaded_from = path


def reset_cache_for_tests() -> None:
    """Test helper — clear the in-memory dedup cache + path pointer."""
    global _dedup_loaded_from
    with _write_lock:
        _dedup_cache.clear()
        _dedup_loaded_from = None


def _append_growth_record(
    record: dict,
    path: Optional[Path] = None,
) -> None:
    """Best-effort append. Never raises."""
    target = path if path is not None else _growth_log_path()
    try:
        line = json.dumps(record, sort_keys=False, default=str)
    except Exception as exc:
        log.debug("growth.serialize_error", error=str(exc))
        return
    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        with open(target, "a", encoding="utf-8") as f:
            f.write(line + "\n")
    except Exception as exc:
        log.debug("growth.write_error", path=str(target), error=str(exc))


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def record_growth_event(
    *,
    api_key: Optional[str],
    ref_code: Optional[str],
    path: Optional[str] = None,
    request_id: Optional[str] = None,
    now: Optional[datetime] = None,
) -> dict:
    """
    Record a growth event. Returns a small diagnostics dict:

      - ``{"action": "recorded", "api_key_hash": "...", "ref_code": "..."}``
      - ``{"action": "deduped",  ...}`` — same pair within 24h.
      - ``{"action": "skipped",  "reason": ...}`` — empty/invalid input.

    Dedup is by ``(api_key_hash, ref_code)`` within
    ``DEDUP_WINDOW_HOURS`` (24). A 25-hour-old duplicate will record
    again (makes sense — we do want to see which refs keep driving
    return usage over time).

    Never raises. Failure to write simply logs at DEBUG and moves
    on; the dedup cache is still updated so the API caller cannot
    hammer the same URL and generate a flood of near-duplicate
    rows on a retry.
    """
    hashed = _hash_api_key(api_key)
    if not hashed:
        return {"action": "skipped", "reason": "no_api_key"}
    cleaned = _sanitize_ref_code(ref_code)
    if not cleaned:
        return {"action": "skipped", "reason": "no_ref_code"}

    current = now if now is not None else datetime.now(timezone.utc)
    if current.tzinfo is None:
        current = current.replace(tzinfo=timezone.utc)

    _ensure_dedup_loaded()
    dedup_key = (hashed, cleaned)
    with _write_lock:
        previous = _dedup_cache.get(dedup_key)
        if previous is not None:
            if previous.tzinfo is None:
                previous = previous.replace(tzinfo=timezone.utc)
            if (current - previous).total_seconds() < DEDUP_WINDOW_SECONDS:
                return {
                    "action": "deduped",
                    "api_key_hash": hashed,
                    "ref_code": cleaned,
                }
        # Reserve the slot under the lock BEFORE we release it — this
        # prevents two concurrent callers from both writing a row for
        # the same (hash, ref) pair within the window.
        _dedup_cache[dedup_key] = current

    record = {
        "timestamp": current.strftime("%Y-%m-%dT%H:%M:%S.%fZ"),
        "api_key_hash": hashed,
        "ref_code": cleaned,
        "path": str(path) if path else "",
        "request_id": str(request_id) if request_id else None,
    }
    _append_growth_record(record)
    return {
        "action": "recorded",
        "api_key_hash": hashed,
        "ref_code": cleaned,
    }


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------


def _read_growth_records(path: Path) -> list[dict]:
    if not path.exists():
        return []
    try:
        raw = path.read_text(encoding="utf-8")
    except Exception:
        return []
    out: list[dict] = []
    for line in raw.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        try:
            parsed = json.loads(stripped)
        except Exception:
            continue
        if isinstance(parsed, dict):
            out.append(parsed)
    return out


def summarize(
    path: Optional[Union[str, Path]] = None,
    *,
    limit: Optional[int] = None,
) -> dict:
    """
    Aggregate the growth log into a ref-level summary.

    Returns a dict of the form::

        {
            "total_events": 42,
            "distinct_refs": 5,
            "distinct_users": 27,
            "refs": [
                {"ref_code": "hn_launch",  "events": 12, "unique_users": 8, "paths": 3},
                ...
            ],
        }

    ``refs`` is sorted by event count descending. ``limit`` caps the
    number of ref rows returned (top-N).
    """
    target = Path(path) if path is not None else _growth_log_path()
    records = _read_growth_records(target)

    per_ref_events: dict[str, int] = defaultdict(int)
    per_ref_users: dict[str, set[str]] = defaultdict(set)
    per_ref_paths: dict[str, set[str]] = defaultdict(set)
    distinct_users_total: set[str] = set()

    for rec in records:
        ref = rec.get("ref_code")
        if not ref:
            continue
        ref = str(ref)
        per_ref_events[ref] += 1
        h = rec.get("api_key_hash")
        if h:
            per_ref_users[ref].add(str(h))
            distinct_users_total.add(str(h))
        rpath = rec.get("path")
        if rpath:
            per_ref_paths[ref].add(str(rpath))

    refs_list = [
        {
            "ref_code": ref,
            "events": per_ref_events[ref],
            "unique_users": len(per_ref_users[ref]),
            "paths": len(per_ref_paths[ref]),
        }
        for ref in per_ref_events
    ]
    refs_list.sort(
        key=lambda r: (r["events"], r["unique_users"]),
        reverse=True,
    )
    if limit is not None and limit > 0:
        refs_list = refs_list[:limit]

    return {
        "total_events": len(records),
        "distinct_refs": len(per_ref_events),
        "distinct_users": len(distinct_users_total),
        "refs": refs_list,
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m trading_bot.api.growth",
        description=(
            "Summarize the growth-loop log (ref-code usage per "
            "distinct user)."
        ),
    )
    parser.add_argument(
        "--summary", action="store_true",
        help="Print a ref-code summary to stdout",
    )
    parser.add_argument(
        "--path", default=None,
        help=(
            "Path to the growth JSONL file "
            f"(default: ${GROWTH_LOG_ENV_VAR} or {DEFAULT_GROWTH_LOG_PATH})"
        ),
    )
    parser.add_argument(
        "--json", action="store_true",
        help="Emit JSON instead of human-readable text",
    )
    parser.add_argument(
        "--top", type=int, default=None,
        help="Limit to the top N ref codes",
    )
    return parser


def _format_summary_text(summary: dict) -> str:
    lines: list[str] = []
    lines.append(
        f"Total growth events    = {summary.get('total_events', 0)}"
    )
    lines.append(
        f"Distinct ref codes     = {summary.get('distinct_refs', 0)}"
    )
    lines.append(
        f"Distinct unique users  = {summary.get('distinct_users', 0)}"
    )
    refs = summary.get("refs") or []
    if not refs:
        lines.append("")
        lines.append("(no ref-code activity recorded)")
        return "\n".join(lines)
    lines.append("")
    header = f"  {'ref_code':<32} {'events':>8} {'unique_users':>13} {'paths':>7}"
    lines.append(header)
    lines.append("  " + "-" * (len(header) - 2))
    for row in refs:
        lines.append(
            f"  {str(row['ref_code'])[:32]:<32} "
            f"{row['events']:>8} "
            f"{row['unique_users']:>13} "
            f"{row['paths']:>7}"
        )
    return "\n".join(lines)


def main(argv: Optional[list[str]] = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)

    if not args.summary:
        parser.print_help(sys.stderr)
        return 2

    summary = summarize(
        path=args.path,
        limit=args.top if args.top and args.top > 0 else None,
    )

    if args.json:
        print(json.dumps(summary, indent=2, sort_keys=False, default=str))
    else:
        print(_format_summary_text(summary))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
