import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { SITE_NAME } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: `Terms of Service for ${SITE_NAME}.`,
};

const EFFECTIVE_DATE = "July 5, 2026";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0b14]">
      <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6">
        <Link
          href="/"
          className="mb-8 inline-flex items-center gap-2 text-sm text-zinc-400 hover:text-white"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to dashboard
        </Link>
        <h1 className="text-3xl font-bold text-white">Terms of Service</h1>
        <p className="mt-2 text-sm text-zinc-500">Effective {EFFECTIVE_DATE}</p>

        <div className="mt-8 space-y-8 text-sm leading-6 text-zinc-300">
          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">
              1. What {SITE_NAME} is
            </h2>
            <p>
              {SITE_NAME}{" "}provides market analytics, momentum signals, paper-trading
              tooling, and portfolio monitoring for US equities. The service is
              provided by the operator of this site (&quot;we&quot;, &quot;us&quot;). By creating an
              account or using the service you agree to these terms.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">
              2. Not financial advice
            </h2>
            <p>
              {SITE_NAME} is an analytics and education tool.{" "}
              <strong className="text-white">
                Nothing in the service is investment, financial, legal, or tax
                advice, and no signal is a recommendation to buy or sell any
                security.
              </strong>{" "}
              We are not a broker-dealer, investment adviser, or fiduciary. Signals
              are generated by automated rules from market data and can be wrong,
              late, or based on incomplete data.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">
              3. Trading risk
            </h2>
            <p>
              Trading equities — especially momentum day-trading of volatile,
              low-float stocks — involves substantial risk of loss. Most day
              traders lose money. Past performance, backtests, and simulated
              (paper) results do not guarantee future results. You are solely
              responsible for any trading decision you make and for compliance
              with the rules of your broker and jurisdiction, including
              pattern-day-trader rules. Never trade money you cannot afford to
              lose.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">
              4. Accounts and API keys
            </h2>
            <p>
              You must provide accurate account information and keep your
              credentials and issued API keys secret. API keys are personal to
              you; generating a new key revokes the previous one. We may suspend
              keys that are shared, abused, or used to exceed plan limits.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">
              5. Subscriptions and billing
            </h2>
            <p>
              Paid plans are billed as recurring subscriptions through Stripe.
              Prices are shown at checkout. You can cancel at any time from the
              billing portal; access continues to the end of the paid period.
              Except where required by law, payments are non-refundable. We may
              change plan pricing or features with notice effective at your next
              renewal.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">
              6. Acceptable use
            </h2>
            <p>
              You may not resell or redistribute signals or data, reverse
              engineer the service, probe or overload our infrastructure, or use
              the service in violation of applicable law or market regulations.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">
              7. Disclaimer of warranties; limitation of liability
            </h2>
            <p>
              The service is provided &quot;as is&quot; without warranties of any kind,
              including availability, accuracy, or fitness for a particular
              purpose. Market data may be delayed or erroneous. To the maximum
              extent permitted by law, our total liability for any claim arising
              from the service is limited to the amounts you paid us in the 12
              months before the claim, and we are not liable for trading losses,
              lost profits, or indirect, incidental, or consequential damages.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">
              8. Termination
            </h2>
            <p>
              You may stop using the service and cancel at any time. We may
              suspend or terminate accounts that violate these terms. Sections 2,
              3, and 7 survive termination.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">9. Changes</h2>
            <p>
              We may update these terms; material changes will be announced in
              the app or by email. Continued use after changes take effect
              constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">10. Contact</h2>
            <p>
              Questions about these terms: contact the operator via the support
              channel listed on your plan or the email on your billing receipt.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
